### ISSUE TITLE
[PE-D][Tester B] `add` command should stack error messages

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F12-3/tp#102]
If there are multiple errors with the fields, the error message only applies to one of the fields making it harder to identify if we messed up multiple fields.

![image.png](https://raw.githubusercontent.com/UdhayaShan1/ped/main/files/b5993950-a1d1-446d-99e9-afcac8bfcc2c.png)

![image.png](https://raw.githubusercontent.com/UdhayaShan1/ped/main/files/ff6f3f8d-e7e3-4567-b3cb-0fab7b72a3ef.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: UdhayaShan1/ped#7

**Comment by agreatdayy** [comment]
to fix this bug, remove the following lines shown in the image in the UG
