### ISSUE TITLE
[PE-D][Tester B] `edit` error messages should be more specific

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-3/tp#117]
If multiple fields are invalid, edit command returns error message for just one field.

![image.png](https://raw.githubusercontent.com/UdhayaShan1/ped/main/files/41206e84-8910-422b-bb37-13cefd3d1037.png)

It should return for all invalid fields.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: UdhayaShan1/ped#13

**Comment by agreatdayy** [comment]
severity shouldnt be high because the command still functions properly. Although it is true that the error message should contain messages for all invalid input, the user can still get their command to work by fixing the invalid fields one by one.
