### ISSUE TITLE
[PE-D][Tester B] `schedule`without arguments is not handled

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F12-3/tp#124]
![image.png](https://raw.githubusercontent.com/UdhayaShan1/ped/main/files/c0aa06cc-73b0-4fec-bdf5-122a001a3007.png)

![image.png](https://raw.githubusercontent.com/UdhayaShan1/ped/main/files/57b66c20-62b0-4c84-94ab-bb0bb557b45b.png)

Schedule without arguments is not handled and there is no specific error message for this.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: UdhayaShan1/ped#17

**Comment by agreatdayy** [comment]
The schedule command will show reminders and events for the next 14 days if no arguments are provided.

SO, this bug report should be rejected.
